# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTest

pod 'Firebase/Core'



  target 'SwiftTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
